#!/usr/bin/env python3
"""Shared helpers for longform-composer scripts.

The helpers intentionally avoid non-standard dependencies. They support the
simple manifest.yaml shape generated by init_longform_project.py and
split_markdown.py. If PyYAML is installed, it is used; otherwise a lightweight
parser extracts the project, artifacts, progress, and chapters fields needed by
these scripts.
"""

from __future__ import annotations

import datetime as _dt
import json
import re
import unicodedata
from pathlib import Path
from typing import Any, Dict, Iterable, List

ALLOWED_STATUSES = {"planned", "draft", "reviewed", "done", "needs_revision", "skipped"}


def now_utc() -> str:
    return _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def slugify(value: str, default: str = "longform-project") -> str:
    normalized = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    normalized = normalized.lower()
    normalized = re.sub(r"[^a-z0-9]+", "-", normalized).strip("-")
    return normalized or default


def safe_filename(value: str, fallback: str) -> str:
    slug = slugify(value, default=fallback)
    return slug[:80].strip("-") or fallback


def count_words(text: str) -> int:
    # Count latin words and CJK characters as a practical mixed-language estimate.
    latin = re.findall(r"[A-Za-z0-9_]+(?:[-'][A-Za-z0-9_]+)?", text)
    cjk = re.findall(r"[\u4e00-\u9fff]", text)
    return len(latin) + len(cjk)


def quote_yaml(value: Any) -> str:
    if value is None:
        return '""'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    text = text.replace("\n", "\\n")
    return f'"{text}"'


def dump_simple_yaml(data: Dict[str, Any]) -> str:
    lines: List[str] = []

    def emit(obj: Any, indent: int, key: str | None = None) -> None:
        prefix = " " * indent
        if isinstance(obj, dict):
            if key is not None:
                lines.append(f"{prefix}{key}:")
                child_indent = indent + 2
            else:
                child_indent = indent
            for child_key, child_value in obj.items():
                emit(child_value, child_indent, str(child_key))
        elif isinstance(obj, list):
            if key is not None:
                lines.append(f"{prefix}{key}:")
                child_indent = indent + 2
            else:
                child_indent = indent
            for item in obj:
                if isinstance(item, dict):
                    lines.append(" " * child_indent + "-")
                    for child_key, child_value in item.items():
                        emit(child_value, child_indent + 2, str(child_key))
                else:
                    lines.append(" " * child_indent + f"- {quote_yaml(item)}")
        else:
            if key is None:
                lines.append(prefix + quote_yaml(obj))
            else:
                lines.append(f"{prefix}{key}: {quote_yaml(obj)}")

    emit(data, 0)
    return "\n".join(lines) + "\n"


def _decode_double_quoted(value: str) -> str:
    """Decode only the escape sequences emitted by quote_yaml."""

    result: List[str] = []
    index = 0
    while index < len(value):
        char = value[index]
        if char == "\\" and index + 1 < len(value):
            next_char = value[index + 1]
            if next_char == "n":
                result.append("\n")
                index += 2
                continue
            if next_char == '"':
                result.append('"')
                index += 2
                continue
            if next_char == "\\":
                result.append("\\")
                index += 2
                continue
        result.append(char)
        index += 1
    return "".join(result)


def _strip_quotes(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        quote = value[0]
        value = value[1:-1]
        if quote == '"':
            return _decode_double_quoted(value)
        return value.replace("''", "'")
    return value


def _parse_scalar(value: str) -> Any:
    raw = value.strip()
    if raw == "":
        return ""
    lowered = raw.lower()
    if lowered == "true":
        return True
    if lowered == "false":
        return False
    if lowered in {"null", "none", "~"}:
        return None
    if (raw.startswith('"') and raw.endswith('"')) or (raw.startswith("'") and raw.endswith("'")):
        return _strip_quotes(raw)
    if re.fullmatch(r"-?\d+", raw):
        try:
            return int(raw)
        except ValueError:
            pass
    if re.fullmatch(r"-?\d+\.\d+", raw):
        try:
            return float(raw)
        except ValueError:
            pass
    return raw


def load_manifest(path: Path) -> Dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    stripped = text.strip()
    if not stripped:
        raise ValueError(f"manifest is empty: {path}")

    if stripped.startswith("{"):
        return json.loads(stripped)

    try:
        import yaml  # type: ignore
    except ImportError:
        return parse_manifest_lite(text)

    try:
        loaded = yaml.safe_load(text)
    except yaml.YAMLError as exc:  # type: ignore[attr-defined]
        raise ValueError(f"cannot parse YAML manifest with PyYAML at {path}: {exc}") from exc
    if not isinstance(loaded, dict):
        raise ValueError(f"manifest root must be a mapping: {path}")
    return loaded


def parse_manifest_lite(text: str) -> Dict[str, Any]:
    """Parse the simple manifest shape emitted by this skill.

    This is not a general YAML parser. It supports top-level scalar fields,
    one-level dictionaries, and a `chapters` list of one-level dictionaries.
    """

    data: Dict[str, Any] = {}
    current_section: str | None = None
    current_chapter: Dict[str, Any] | None = None

    for raw_line in text.splitlines():
        if not raw_line.strip() or raw_line.lstrip().startswith("#"):
            continue
        indent = len(raw_line) - len(raw_line.lstrip(" "))
        line = raw_line.strip()

        if indent == 0:
            current_chapter = None
            if line.endswith(":"):
                current_section = line[:-1]
                data[current_section] = [] if current_section == "chapters" else {}
            elif ":" in line:
                key, value = line.split(":", 1)
                data[key.strip()] = _parse_scalar(value)
                current_section = None
            continue

        if current_section == "chapters":
            if line == "-":
                current_chapter = {}
                data.setdefault("chapters", []).append(current_chapter)
                continue
            if line.startswith("- "):
                current_chapter = {}
                data.setdefault("chapters", []).append(current_chapter)
                remainder = line[2:].strip()
                if ":" in remainder:
                    key, value = remainder.split(":", 1)
                    current_chapter[key.strip()] = _parse_scalar(value)
                continue
            if current_chapter is not None and ":" in line:
                key, value = line.split(":", 1)
                current_chapter[key.strip()] = _parse_scalar(value)
            continue

        if current_section and isinstance(data.get(current_section), dict) and ":" in line:
            key, value = line.split(":", 1)
            data[current_section][key.strip()] = _parse_scalar(value)

    data.setdefault("chapters", [])
    return data


def manifest_path(root: Path) -> Path:
    return root / "manifest.yaml"


def load_project(root: Path) -> Dict[str, Any]:
    path = manifest_path(root)
    if not path.exists():
        raise FileNotFoundError(f"manifest not found: {path}")
    return load_manifest(path)


def write_manifest(root: Path, manifest: Dict[str, Any]) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    path = manifest_path(root)
    path.write_text(dump_simple_yaml(manifest), encoding="utf-8")
    return path


def default_chapter_titles() -> List[str]:
    return [
        "executive overview",
        "background and problem framing",
        "core concepts and architecture",
        "implementation workflow",
        "examples and patterns",
        "risks limitations and mitigations",
        "checklist and next steps",
    ]


def make_chapter_records(chapter_titles: Iterable[str], target_words: int = 1500, status: str = "planned") -> List[Dict[str, Any]]:
    records: List[Dict[str, Any]] = []
    for idx, title in enumerate(chapter_titles, start=1):
        title = str(title).strip() or f"chapter {idx}"
        chapter_id = f"{idx:02d}"
        filename = f"{chapter_id}_{safe_filename(title, f'chapter-{chapter_id}')}.md"
        records.append(
            {
                "id": chapter_id,
                "title": title,
                "file": f"chapters/{filename}",
                "status": status,
                "target_words": target_words,
                "dependencies": "",
                "summary": "",
                "quality_flags": "",
            }
        )
    return records


def build_manifest(
    title: str,
    output_root: Path,
    chapters: Iterable[str],
    delivery_mode: str = "file-first",
    target_audience: str = "expert",
    target_depth: str = "comprehensive",
    language: str = "auto",
    style: str = "clear, structured, domain-appropriate",
    user_request: str = "",
    target_words: int = 1500,
    chapter_status: str = "planned",
) -> Dict[str, Any]:
    slug = output_root.name or slugify(title)
    chapter_records = make_chapter_records(chapters, target_words=target_words, status=chapter_status)
    return {
        "schema_version": "1.0",
        "project": {
            "title": title,
            "slug": slug,
            "created_at": now_utc(),
            "delivery_mode": delivery_mode,
            "target_audience": target_audience,
            "target_depth": target_depth,
            "language": language,
            "user_request": user_request,
        },
        "constraints": {
            "max_chapter_words": target_words,
            "citation_policy": "follow the active environment rules",
            "style": style,
        },
        "artifacts": {"index": "index.md", "final": "final/final_merged.md"},
        "progress": {"current_phase": "planning", "current_chapter_id": "01" if chapter_records else ""},
        "chapters": chapter_records,
    }


def normalize_status(value: Any) -> str:
    return str(value or "planned").strip().lower()


def get_title(manifest: Dict[str, Any], fallback: str = "Longform Deliverable") -> str:
    project = manifest.get("project") if isinstance(manifest.get("project"), dict) else {}
    return str(project.get("title") or fallback)


def get_chapters(manifest: Dict[str, Any]) -> List[Dict[str, Any]]:
    chapters = manifest.get("chapters", [])
    return chapters if isinstance(chapters, list) else []


def chapter_path(root: Path, chapter: Dict[str, Any]) -> Path:
    return root / str(chapter.get("file", ""))


def chapter_anchor(title: str) -> str:
    text = title.strip().lower()
    text = re.sub(r"[`*_\[\](){}:;,.!?/\\|]+", "", text)
    text = re.sub(r"\s+", "-", text)
    return text.strip("-") or "chapter"


def demote_headings(markdown: str, levels: int = 1) -> str:
    lines: List[str] = []
    for line in markdown.splitlines():
        match = re.match(r"^(#{1,6})(\s+.*)$", line)
        if match:
            hashes = match.group(1)
            suffix = match.group(2)
            new_level = min(6, len(hashes) + levels)
            lines.append("#" * new_level + suffix)
        else:
            lines.append(line)
    return "\n".join(lines).strip() + "\n"


def read_nonempty(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def update_index(root: Path, manifest: Dict[str, Any]) -> Path:
    title = get_title(manifest)
    chapters = get_chapters(manifest)
    lines = [f"# {title}", "", "## Reading guide", "", "This index is generated from manifest.yaml.", "", "## Table of contents", ""]
    for chapter in chapters:
        cid = str(chapter.get("id", ""))
        ctitle = str(chapter.get("title", "untitled"))
        cfile = str(chapter.get("file", ""))
        status = normalize_status(chapter.get("status"))
        lines.append(f"- `{cid}` [{ctitle}]({cfile}) - `{status}`")
    lines.extend(["", "## Final artifact", "", "- [final merged markdown](final/final_merged.md)", ""])
    path = root / "index.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_progress_log(root: Path, message: str) -> Path:
    logs = root / "logs"
    logs.mkdir(parents=True, exist_ok=True)
    path = logs / "progress.md"
    previous = path.read_text(encoding="utf-8") if path.exists() else "# Progress log\n\n"
    entry = f"- {now_utc()} - {message}\n"
    path.write_text(previous.rstrip() + "\n" + entry, encoding="utf-8")
    return path


def create_chapter_stub(title: str) -> str:
    return f"""# {title}

> chapter objective: define the purpose of this chapter before drafting the final content.

## core content

<!-- write chapter content here -->

## examples or implementation details

<!-- add examples, code, tables, or checklists when useful -->

## chapter summary

<!-- summarize the chapter in 3-5 bullets or a concise paragraph -->

## handoff to next chapter

<!-- explain how the next chapter continues the argument -->
"""


def ensure_project_structure(root: Path) -> None:
    for relative in ["chapters", "final", "logs", "notes", "sources"]:
        (root / relative).mkdir(parents=True, exist_ok=True)
